### ISSUE TITLE
[Feature]: python3.8跑不了，可以适配一下吗老哥，枯了

### ISSUE THREAD

**Issue by Laurc2004** [A-kirami/nonebot-plugin-template#1]
### 报告清单

- [x] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认功能并未实现。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的需求。
- [X] 我有足够的时间和能力，愿意为此提交 PR 来实现功能。

### 您希望能解决什么样的问题？

可适配python3.8跑此项目

### 您想要的解决方案

作者能实现就行

**Comment by lgc2333** [comment]
？

**Comment by A-kirami** [comment]
这是项目模板，不是插件
