### ISSUE TITLE
BUG: 无法跑流程

### ISSUE THREAD

**Issue by SydrrO** [A-kirami/nonebot-plugin-template#4]
### 确认事项

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确认问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。

### 影响版本

a5dccd78aa709077ce39f280ea59de991dc6718c

## 您好，我按照您的指示做了这样的准备：
![image](https://github.com/A-kirami/nonebot-plugin-template/assets/129657153/6d0024cd-ddad-47a0-affe-18f59ae982b6)

![image](https://github.com/A-kirami/nonebot-plugin-template/assets/129657153/4eb62069-0579-4be7-ad8e-48d723b1ece3)

## 这是错误提示：

![image](https://github.com/A-kirami/nonebot-plugin-template/assets/129657153/79617eaf-5f02-4370-b753-6f4164b1f402)

![image](https://github.com/A-kirami/nonebot-plugin-template/assets/129657153/ac620ecb-d735-4858-9c09-8999b71fdf74)
### 复现步骤

**首先按照您的指示拷贝仓库，设置MIT。其次发布第一个tag，然后流程就显示出错，build wheel出问题**

### 额外补充

**我已在上文提交，辛苦辛苦**  :

### 参与贡献

- [X] 我有足够的时间和能力，愿意为此提交 PR 来修复问题。

**Comment by A-kirami** [comment]
我查看了你对应的仓库，发现你使用的包管理器是 poetry，由于 poetry 使用的不是 pyproject.toml 标准格式，因此无法使用。

本仓库的工作流需要 pyproject.toml 标准格式才可运行，你可以使用支持标准格式的 [pdm](https://pdm.fming.dev/latest/) 作为包管理器。

**Comment by SydrrO** [comment]
> 我查看了你对应的仓库，发现你使用的包管理器是 poetry，由于 poetry 使用的不是 pyproject.toml 标准格式，因此无法使用。
> 
> 本仓库的工作流需要 pyproject.toml 标准格式才可运行，你可以使用支持标准格式的 [pdm](https://pdm.fming.dev/latest/) 作为包管理器。

好的，非常感谢您的回复，谢谢
